// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfMMHUAW_AaEhCnsbUlW53QVEjJ17yS4s',
    appId: '1:297669647148:web:2c0e3a28294e45c140aa89',
    messagingSenderId: '297669647148',
    projectId: 'riseup-e8f47',
    authDomain: 'riseup-e8f47.firebaseapp.com',
    storageBucket: 'riseup-e8f47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsg--TD-3eAyhX4W_vbptkJTtU1tZ67I4',
    appId: '1:297669647148:android:9c5e10cd97a1f4ef40aa89',
    messagingSenderId: '297669647148',
    projectId: 'riseup-e8f47',
    storageBucket: 'riseup-e8f47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-VVP6z7Qd2MunlU1wXjdh6kbpWdWEgg',
    appId: '1:297669647148:ios:4b186bc0e3be7bf240aa89',
    messagingSenderId: '297669647148',
    projectId: 'riseup-e8f47',
    storageBucket: 'riseup-e8f47.firebasestorage.app',
    iosBundleId: 'com.example.riseup',
  );
}
